### ISSUE TITLE
Panic when a counter has an starting value of integer and then a float is pushed

### ISSUE THREAD

**Issue by slok** [sinkingpoint/openmetrics-parser#2]
Hi!

First of all thanks for this project, specially [gravel-gateway](https://github.com/sinkingpoint/prometheus-gravel-gateway). I think that currently is the most usable/helpful Prometheus gateway out there.

### Context

I encontered this problem while using `gravel-gateway`. However seems that the problem is related with the usage of this library, so I open the issue here, if you prefer to have the issue on the other repo, I will move it happily.

### Problem

The problem itself is when I push a `counter` metric and randomly crashes the gateway with this error:

```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/openmetrics-parser-0.4.2/src/public/model.rs:900:50
```

### Findings
After reading some code (I don't know Rust) and making some tests I found that this happens when a counter has an integer value. E.g:

```
example_test_counter_total{foo="bar"} 0
```

And then a float is pushed. e.g:

```
example_test_counter_total{foo="bar"} 0.01
```

After this second push, the gateway crashes, but, if the metric starts with a float from the begining, there are no crashes, however is very common to initialize a metric to 0, leading to this use case.

### Extra info

More information that could help:

- Gravel gateway version: `v1.6.2`
- Prometheus client: `github.com/prometheus/client_golang v1.17.0`
- Using the [official process collector](https://pkg.go.dev/github.com/prometheus/client_golang@v1.17.0/prometheus/collectors#NewProcessCollector) leads to this crashes on `process_cpu_seconds_total` counter metric.

**Comment by sinkingpoint** [comment]
Interesting! I'll take a look

**Comment by sinkingpoint** [comment]
This is fixed - will get a gravel gateway out with this soon
